import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navigation from "./_components/Navigation";

const rubik = Rubik({
  variable: "--font-rubik-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.className} antialiased`}>
        <main className="flex flex-col sm:flex-row h-screen">
          <Navigation />
          <div className="flex-1 h-full overflow-auto min-w-0">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
